import { useState, useEffect } from "react";

/**
 * A health signal tracked on the project dashboard (e.g. test coverage, security score).
 */
export interface HealthSignal {
  /** Display name of the health signal. */
  name: string;
  /** Current status level. */
  status: "good" | "warning" | "critical";
  /** Optional numeric score (0-100). */
  score?: number;
  /** Human-readable summary of the signal state. */
  summary: string;
}

/**
 * A risk item with severity classification.
 */
export interface Risk {
  /** Unique risk identifier. */
  id: string;
  /** Display name of the risk. */
  name: string;
  /** Severity classification. */
  severity: "low" | "medium" | "high";
  /** Human-readable risk description. */
  summary: string;
}

/**
 * A suggested action generated by the AI-first orchestrator.
 */
export interface SuggestedAction {
  /** Unique action identifier. */
  id: string;
  /** Action title. */
  title: string;
  /** Detailed action description. */
  description: string;
  /** Type of action (e.g. "transition", "implement"). */
  actionType: string;
  /** Priority level: p0 (critical), p1 (important), p2 (nice-to-have). */
  priority: "p0" | "p1" | "p2";
}

/**
 * A knowledge sync event tracking doc/state consistency.
 */
export interface SyncEvent {
  /** Unique sync event identifier. */
  id: string;
  /** Current resolution status. */
  status: "suggested" | "pending" | "confirmed" | "dismissed";
  /** Human-readable description of the sync event. */
  summary: string;
}

/**
 * A single entry in the project timeline.
 */
export interface TimelineEntry {
  /** ISO 8601 timestamp string. */
  timestamp: string;
  /** Tag categorizing the event (e.g. "STAGE_TRANSITION", "QA_COMPLETE"). */
  tag: string;
  /** Human-readable event message. */
  message: string;
}

/**
 * A single data point on a trend chart.
 */
export interface TrendPoint {
  /** X-axis label (e.g. date string). */
  label: string;
  /** Numeric value (0-100). */
  value: number;
}

/**
 * The full project data payload consumed by the dashboard.
 */
export interface ProjectData {
  /** Project display name. */
  name: string;
  /** Current lifecycle stage identifier. */
  currentStage: string;
  /** Human-readable stage label for display. */
  stageLabel: string;
  /** Project mode (greenfield or brownfield). */
  mode: string;
  /** Overall project status. */
  status: string;
  /** Health signals to render as health cards. */
  healthSignals: HealthSignal[];
  /** Risk items for the risk list and heatmap. */
  risks: Risk[];
  /** Suggested actions for the actions grid. */
  suggestedActions: SuggestedAction[];
  /** Knowledge sync events for the sync status panel. */
  syncEvents: SyncEvent[];
  /** Recent timeline entries for the activity feed. */
  recentTimeline: TimelineEntry[];
  /** Trend data for the health trend chart. */
  healthTrend: TrendPoint[];
}

/**
 * Custom hook that loads project data from the static data module.
 *
 * Returns the parsed `ProjectData` (or `null` if loading) and a `loading` boolean.
 * The data is loaded once on mount via a dynamic import.
 *
 * @returns An object with `data` (ProjectData | null) and `loading` (boolean)
 */
export function useProjectData(): { data: ProjectData | null; loading: boolean } {
  const [data, setData] = useState<ProjectData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const mod = await import("../data/project-data.js");
        const raw = mod.default;
        setData({
          ...raw,
          stageLabel: raw.currentStage,
        });
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  return { data, loading };
}
